name: Sync

on:
  push:
    branches: [master]
  schedule:
    - cron: '5 2 * * *' # Run at 2.05 UTC each day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync
      run: |
        yarn install
        SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }} AIRTABLE_API_TOKEN=${{ secrets.AIRTABLE_API_TOKEN }} ECOMAIL_API_TOKEN=${{ secrets.ECOMAIL_API_TOKEN}} yarn dev
